### ISSUE TITLE
Nvidia GPU not visible in post script

### ISSUE THREAD

**Issue by dcbr** [apptainer/apptainer#1314]
### Version of Apptainer

`apptainer version 1.1.8-1`

### Expected behavior

The build should succeed and the GPU should be visible while the post script is executed.

### Actual behavior

The build fails with the message

```sh
INFO:    Running post scriptlet
+ nvidia-smi
/.post.script: 1: /.post.script: nvidia-smi: not found
FATAL:   While performing build: while running engine: exit status 127
```

When the post script is commented out, the build succeeds and the container runs fine (i.e. `nvidia-smi` is correctly recognized in the test and run scripts).

<details><summary>Output of build without post script</summary>

```sh
INFO:    Adding runscript
INFO:    Adding testscript
INFO:    Running testscript
Wed May  3 11:23:40 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   36C    P0    31W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
INFO:    Creating SIF file...
INFO:    Build complete: test.sif
```

</details>
<details><summary>Output of running the image</summary>

```sh
INFO:    underlay of /etc/localtime required more than 50 (66) bind mounts
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (198) bind mounts
Wed May  3 11:30:32 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   37C    P0    31W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

</details>

### Steps to reproduce this behavior

Using following definition file (`test.def`)

```
Bootstrap: docker
From: ubuntu:18.04

%post
    nvidia-smi

%test
    nvidia-smi

%runscript
    nvidia-smi
```

and using the commands `apptainer build --nv test.sif test.def` for building (fails unless the post section is commented out) and `apptainer run --nv test.sif` for running the image.

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

Not sure, this is a shared HPC environment. I asked the administrators for further details and support but was wondering if something else could be causing this behavior.

**Comment by GodloveD** [comment]
Just to make sure, you are building with the `--nv` flag right?

I just did a test and it seems like the `--nv` flag does bind mount the appropriate libraries into `/.singularity.d/libs` at build time.  I don't know why it skips the binary.  

But the question also arises, why do you need `nvidia-smi` in post?  The libraries are all there in the (unlikely?) event that you need to compile something against the driver libraries themselves.  But in the vast majority of cases, you do not need access to these libraries even if you are installing CUDA and building GPU enabled applications.

**Comment by dcbr** [comment]
Yes this is using the `--nv` flag for the build. But you are indeed correct that the appropriate libraries are correctly bound before running the post script (this is also visible in the debug logs below). I was using `nvidia-smi` just as a sanity check to see whether the GPU was available from within the container (and post/test scripts).
```
INFO    [U=0,P=1]          runPostScript()               Running post scriptlet
...
DEBUG   [U=0,P=104]        setNVLegacyConfig()           Using legacy binds for nv GPU setup
VERBOSE [U=0,P=104]        NvidiaIpcsPath()              persistenced socket /var/run/nvidia-persistenced/socket not found
...
WARNING [U=0,P=104]        setGPUBinds()                 nv files may not be bound with --writable
...
DEBUG   [U=0,P=104]        addLibsMount()                Add library /lib64/libcuda.so.1 to mount list
...
DEBUG   [U=0,P=104]        addFilesMount()               Adding file /bin/nvidia-smi:/usr/bin/nvidia-smi to mount list
...
DEBUG   [U=0,P=104]        mountGeneric()                Mounting /lib64/libcuda.so.1 to /var/apptainer/mnt/session/libs/libcuda.so.1
DEBUG   [U=0,P=104]        mountGeneric()                Remounting /var/apptainer/mnt/session/libs/libcuda.so.1
...
DEBUG   [U=0,P=104]        mountGeneric()                Mounting /bin/nvidia-smi to /var/apptainer/mnt/session/rootfs/usr/bin/nvidia-smi
WARNING [U=0,P=104]        mountGeneric()                Skipping mount /bin/nvidia-smi [files]: /usr/bin/nvidia-smi doesn't exist in container
...
DEBUG   [U=0,P=124]        sylogBuiltin()                Running action command exec
DEBUG   [U=0,P=104]        PostStartProcess()            Post start process
+ nvidia-smi
/.post.script: 1: /.post.script: nvidia-smi: not found
```
The original problem I was facing is resolved and was unrelated, so this issue can be closed. It is still a bit confusing/unexpected that these binaries are not available though, so I'll leave that to you in case you decide to investigate this further.
Either way, thanks for the quick response!

**Comment by colobas** [comment]
This is still an issue for me. A package I'm installing expects to find `nvidia-smi` at build time.

**Comment by JasonYangShadow** [comment]
> mount /bin/nvidia-smi [files]: /usr/bin/nvidia-smi doesn't exist in container

```
WARNING [U=0,P=104]        mountGeneric()                Skipping mount /bin/nvidia-smi [files]: /usr/bin/nvidia-smi doesn't exist in container
```
the above message is already WARNING level?

**Comment by DrDaveD** [comment]
Oh, that's because the build command runs a nested apptainer command for the postscript section, and [runs it using `-s`](https://github.com/apptainer/apptainer/blob/release-1.3/internal/pkg/build/stage.go#L86) which silences warnings.  If it used `-q` instead it would only hide info messages and not warnings.  The question is if that would be too noisy for other operations.  It also runs a nested apptainer for the test section, but if even if we change it to `-q` for the post section I think we wouldn't want it to be also changed for test because then the warnings would show up twice.

I tried changing it from `-s` to `-q` and even without `--nv` it includes a warning
```
WARNING: No current working directory set: skipping mount
```
so we would at least need to prevent that.
